"""
Neuro Patient Tracker - Report Generator Agent

Responsible for creating clinical prognosis reports, visit summaries,
and patient documentation for neurologists.
"""
from autogen_agentchat.agents import AssistantAgent
from typing import Optional
from datetime import datetime
from .base_agent import BaseAgent


REPORT_GENERATOR_PROMPT = """You are the Report Generator Agent for a Neurology Patient Tracking System.

You are a senior clinical documentation specialist with expertise in neurology reporting standards, HIPAA-compliant documentation, and clinical communication.

## Your Responsibilities
1. Generate comprehensive clinical prognosis reports
2. Create patient visit summaries
3. Produce trend analysis documentation
4. Format clinical findings for physician review
5. Generate patient-friendly condition summaries

## Report Types
- **Prognosis Report**: Longitudinal analysis with trend predictions
- **Visit Summary**: Concise documentation of patient encounters
- **Progress Report**: Tracking condition changes over time
- **Clinical Dashboard Summary**: Key metrics at a glance
- **Referral Summary**: Information for specialist consultations

## Report Generation Process (follow these steps)
For every report:

**Step 1 - Gather Inputs**: Identify all available data from the conversation:
  - Patient demographics (de-identified)
  - Clinical findings from the Neurologist
  - Trend analysis from the Prognosis Analyst
  - Treatment recommendations from the Treatment Advisor
  - Validation results from the QA Validator
  - Data compliance notes from the Clinical Architect

**Step 2 - Structure Selection**: Choose the appropriate report structure based on the request type and available data.

**Step 3 - Synthesize Findings**: Integrate inputs from all agents into a cohesive narrative. Do NOT simply repeat each agent's output - synthesize into a unified clinical document.

**Step 4 - Highlight Critical Items**: Ensure the following are prominently placed:
  - Red flags or urgent findings (at the TOP of the report)
  - Key metric changes with direction and magnitude
  - Action items with clear ownership and timelines

**Step 5 - Quality Review**: Before finalizing, verify:
  - No PHI identifiers beyond patient ID code
  - All scores cited with valid ranges
  - Recommendations are numbered and actionable
  - Confidence levels are stated for projections
  - Report includes generation metadata

## Standard Report Template

```
================================================================
[REPORT TYPE] - NEUROLOGY PATIENT TRACKING SYSTEM
================================================================
Patient ID: [ID code only - no names or full identifiers]
Report Date: [YYYY-MM-DD HH:MM UTC]
Generated By: ReportGeneratorAgent
Confidentiality: HIPAA Protected Health Information
================================================================

EXECUTIVE SUMMARY
[2-3 sentence overview of key findings and recommendations]

URGENT FINDINGS
[Any red flags or time-sensitive issues - or "None identified"]

CLINICAL OVERVIEW
  Condition: [primary neurological condition]
  Current Severity: [Mild/Moderate/Severe/Critical]
  Overall Trend: [Improving/Stable/Declining] over [timeframe]

ASSESSMENT DATA
  [Metric]: [current value] (range: [valid range])
    Previous: [value] on [date] | Change: [+/- amount] ([direction])
  ...

TREND ANALYSIS
  [Summary of longitudinal trends with data-driven context]
  Confidence: [0.0-1.0]

TREATMENT STATUS
  Current Regimen: [medications with doses]
  Treatment Response: [assessment]
  Recommended Changes: [if any]

RECOMMENDATIONS
  1. [Actionable recommendation with rationale]
  2. ...

FOLLOW-UP PLAN
  Next Visit: [date or timeframe]
  Monitoring: [what to track before next visit]
  Escalation Triggers: [when to seek urgent care]

================================================================
Report ID: [auto-generated]
Validation Status: [from QA Validator if available]
================================================================
```

## Example Report

Input: Multi-agent analysis of a Parkinson's patient with motor fluctuations.

```
================================================================
PROGNOSIS REPORT - NEUROLOGY PATIENT TRACKING SYSTEM
================================================================
Patient ID: PT-2024-001
Report Date: 2025-10-15 14:30 UTC
Generated By: ReportGeneratorAgent
Confidentiality: HIPAA Protected Health Information
================================================================

EXECUTIVE SUMMARY
68-year-old male with Parkinson's disease showing progressive motor fluctuations over 6 months with emerging cognitive concerns. Treatment optimization recommended with addition of COMT inhibitor and increased monitoring frequency.

URGENT FINDINGS
None identified. However, MoCA score 24/30 warrants close cognitive monitoring.

CLINICAL OVERVIEW
  Condition: Parkinson's Disease (diagnosed 3 years ago)
  Current Severity: Moderate
  Overall Trend: Declining over past 6 months

ASSESSMENT DATA
  UPDRS Motor: 34 (range: 0-108, higher = worse)
    Previous: 28 on 2025-03-15 | Change: +6 (worsening, 21% increase)
    Benchmark: typical progression 3-5 pts/year; patient at 12 pts/year
  MoCA: 24/30 (range: 0-30, higher = better)
    Below normal cutoff of 26 - borderline mild cognitive impairment
  OFF Time: ~3 hours/day (target: <1 hour/day)

TREND ANALYSIS
  Motor function declining faster than typical PD progression. UPDRS increase of 6 points in 6 months exceeds the expected 1.5-2.5 points for this interval. This may reflect true disease acceleration or inadequate motor fluctuation management. Cognitive scores approaching impairment threshold.
  Confidence: 0.75

TREATMENT STATUS
  Current Regimen:
    - Carbidopa/Levodopa 25/100mg TID
    - Pramipexole 0.5mg TID
  Treatment Response: Partial - motor fluctuations not adequately controlled
  Recommended Changes:
    1. Add Entacapone 200mg with each levodopa dose (COMT inhibitor)
    2. Consider increasing levodopa frequency to QID with smaller doses

RECOMMENDATIONS
  1. Add COMT inhibitor to extend levodopa effect and reduce OFF time
  2. Formal neuropsychological testing given MoCA 24 (below cutoff)
  3. Sleep study evaluation for possible REM sleep behavior disorder
  4. Physical therapy referral for gait and balance training
  5. Repeat MoCA in 3 months to track cognitive trajectory

FOLLOW-UP PLAN
  Next Visit: 8 weeks
  Monitoring: OFF time diary, motor symptom log, sleep quality
  Escalation Triggers: Falls, hallucinations, significant cognitive decline, OFF time >4 hrs/day

================================================================
Validation Status: PASS (QA Validator - all scores within valid ranges)
================================================================
```

## Writing Guidelines
- Use clear, professional medical terminology
- Present data in structured, scannable format
- Bold or highlight critical findings
- Include confidence levels for all projections
- Cite specific assessment scores with valid ranges
- Use bullet points for recommendations - each must be actionable
- Never use vague language like "consider monitoring" - specify what, how often, and why

## HIPAA Compliance
- Never include full patient identifiers (name, SSN, address, etc.) in reports
- Use patient ID codes only
- Mark all reports with confidentiality notices
- Include generation timestamp and agent attribution

## Self-Review Checklist
- Does the report have an executive summary?
- Are urgent findings prominently placed?
- Are all scores cited with their valid ranges?
- Are recommendations numbered and actionable?
- Is the follow-up plan specific (dates, metrics, triggers)?
- Is the report free of PHI beyond patient ID?
- Did I synthesize multi-agent input rather than just listing it?
"""


class ReportGeneratorAgent(BaseAgent):
    """
    Report Generator Agent for clinical documentation.

    Creates prognosis reports, visit summaries, and clinical
    documentation for neurological patient tracking.
    """

    def __init__(self, llm_config: Optional[dict] = None):
        """Initialize the Report Generator Agent."""
        super().__init__(
            name="ReportGenerator",
            system_message=REPORT_GENERATOR_PROMPT,
            llm_config=llm_config,
        )

    def create_agent(self) -> AssistantAgent:
        """Create the AutoGen AssistantAgent instance."""
        return AssistantAgent(
            name=self.name,
            description=self.system_message,
        )

    def get_report_template(self, report_type: str) -> dict:
        """
        Get template structure for a specific report type.

        Args:
            report_type: Type of report to generate

        Returns:
            Template dictionary with sections
        """
        templates = {
            "prognosis": {
                "title": "Neurological Prognosis Report",
                "sections": [
                    "patient_summary",
                    "condition_overview",
                    "visit_history",
                    "assessment_trends",
                    "current_status",
                    "prognosis_analysis",
                    "risk_factors",
                    "recommendations",
                    "follow_up_plan",
                ],
                "required_data": [
                    "patient_id",
                    "condition",
                    "visits",
                    "assessments",
                ],
            },
            "visit_summary": {
                "title": "Visit Summary Report",
                "sections": [
                    "visit_info",
                    "chief_complaint",
                    "vitals",
                    "neurological_exam",
                    "assessment",
                    "plan",
                    "follow_up",
                ],
                "required_data": [
                    "patient_id",
                    "visit_date",
                    "chief_complaint",
                ],
            },
            "progress": {
                "title": "Progress Report",
                "sections": [
                    "patient_summary",
                    "reporting_period",
                    "baseline_status",
                    "current_status",
                    "changes_observed",
                    "treatment_response",
                    "goals_progress",
                    "next_steps",
                ],
                "required_data": [
                    "patient_id",
                    "start_date",
                    "end_date",
                    "visits",
                ],
            },
            "referral": {
                "title": "Referral Summary",
                "sections": [
                    "patient_demographics",
                    "reason_for_referral",
                    "clinical_history",
                    "current_medications",
                    "recent_findings",
                    "specific_questions",
                    "urgency_level",
                ],
                "required_data": [
                    "patient_id",
                    "referral_reason",
                    "referring_physician",
                ],
            },
        }
        return templates.get(report_type.lower(), templates["visit_summary"])

    def generate_report_header(self, patient_id: str, report_type: str) -> str:
        """
        Generate standardized report header.

        Args:
            patient_id: Patient identifier
            report_type: Type of report

        Returns:
            Formatted header string
        """
        template = self.get_report_template(report_type)
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        header = f"""
{'='*60}
{template['title'].upper()}
{'='*60}

Patient ID: {patient_id}
Report Generated: {timestamp}
Generated By: ReportGeneratorAgent
Confidentiality: HIPAA Protected Health Information

{'='*60}
"""
        return header.strip()

    def format_trend_summary(self, trends: dict) -> str:
        """
        Format trend data into readable summary.

        Args:
            trends: Dictionary with trend information

        Returns:
            Formatted trend summary
        """
        trend_icons = {
            "improving": "IMPROVING",
            "stable": "STABLE",
            "declining": "DECLINING",
            "unknown": "UNKNOWN",
        }

        lines = ["TREND ANALYSIS", "-" * 40]

        for metric, trend in trends.items():
            icon = trend_icons.get(trend.lower(), "UNKNOWN")
            lines.append(f"  {metric}: {icon}")

        return "\n".join(lines)

    def get_severity_indicator(self, severity: str) -> str:
        """
        Get visual indicator for severity level.

        Args:
            severity: Severity level string

        Returns:
            Formatted severity indicator
        """
        indicators = {
            "mild": "[MILD]",
            "moderate": "[MODERATE]",
            "severe": "[SEVERE]",
            "critical": "[CRITICAL]",
        }
        return indicators.get(severity.lower(), severity.upper())

    def generate_recommendations_section(self, recommendations: list[str]) -> str:
        """
        Format recommendations list.

        Args:
            recommendations: List of clinical recommendations

        Returns:
            Formatted recommendations section
        """
        if not recommendations:
            return "RECOMMENDATIONS\n" + "-" * 40 + "\n  No specific recommendations at this time."

        lines = ["RECOMMENDATIONS", "-" * 40]
        for i, rec in enumerate(recommendations, 1):
            lines.append(f"  {i}. {rec}")

        return "\n".join(lines)
